genres: 
  - Acoustic
  - Ambient 
  - Classical
  - Jazz and Blues
  - Dance / Electronic
  - Hip Hop
  - Pop
  - Reggae
  - Rock
  - Indie
questions:
  - What''s the name of your first pet?
  - What was the name of your school?
